### ISSUE TITLE
about the segmentation result

### ISSUE THREAD

**Issue by zedyasuotalong** [VendenIX/BrainMetaSegmentatorUI-Front#2]
Hello,
 after the segmentation, the segmentation result seems can not be shown, could you tell me why and how to solve this problem?
the followings are some debug log:
the back-end:
![image](https://github.com/user-attachments/assets/aa7e5eed-87c7-467b-8118-b08f5885dd5f)
the front-end:
![image](https://github.com/user-attachments/assets/f5d5148f-b5de-4b93-bfd7-4ea86b3e2482)

**Comment by VendenIX** [comment]
Hi 
Everything seems functional. The model found 0 rois, as indicated in the console after the line "applyUNETR 1 342 342 16": "Le modèle à trouvé 0 rois", and when an RTStruct has 0 rois, we cannot display it on the viewer. Otherwise, do the medical data you are using have metastases? Also, which weights are you using? I'm not sure that it can work with only the default pretrained weights. The performance may not be optimal without the right weights. I cannot share the weights I used before publishing an article. Our training dataset used 512 by 512 images with a pixel spacing of 0.5 by 0.5 and a thickness of 1, for your information. Otherwise, do you have any feedback on the Front-end or Back-end parts of this project? 👀

**Comment by zedyasuotalong** [comment]
Thank you,
Does "The model found 0 rois" mean the model did not find any foreground targets except for the background? If so, maybe I need to try medical data related to model detection targets(metastases).  I'm using the default pretrained weights. Could you please tell me which sub-task dataset from MSD is being used?

One feedback for Back-end: I can not execute "pip install -r requirements.txt" successfully, so I install the requirements in .txt gradully, which results in some conflicts between libraries. 
More feedback will be provided after my development based on this framework

**Comment by VendenIX** [comment]
Yes it mean that he found no targets. The model is finetuned for the segmentation of metastases, trained from the pretrained weights and private data that I don't have and can't share and the originals pretrained weights are from the challenge BTCV  : https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/unetr_btcv_segmentation_3d.ipynb 
Thx for the feedback arround the requirements, I will try to make it easier. 
If you want free data for a training, it is hard to find it on the web, but you can try  : 
https://www.cancerimagingarchive.net/
https://www.kaggle.com
